# install dependecies
FROM node:22 AS Deps
WORKDIR /app
COPY package*.json .
RUN npm install --only=production

# build app
FROM node:22 AS Builder
WORKDIR /app
COPY --from=Deps /app/node_modules ./node_modules
COPY . .
# For Typescript backend, uncomment the following line
# RUN npm run build

# run app
FROM node:alpine AS Runtime
WORKDIR /app
COPY --from=Builder /app ./
EXPOSE 5000
CMD ["npm", "run", "start"]
